# Generated by Django 3.1.3 on 2021-06-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210610_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
